CREATE TABLE IF NOT EXISTS order_intent_queue (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  intentKey VARCHAR(191) NOT NULL,
  fifoKey VARCHAR(191) NOT NULL,
  uid INT UNSIGNED NOT NULL,
  pid INT UNSIGNED NOT NULL,
  strategyCategory VARCHAR(20) NOT NULL,
  intentType VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  priority INT NOT NULL DEFAULT 100,
  attemptCount INT NOT NULL DEFAULT 0,
  maxAttempts INT NOT NULL DEFAULT 3,
  lockedBy VARCHAR(80) DEFAULT NULL,
  lockedAt DATETIME DEFAULT NULL,
  availableAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  startedAt DATETIME DEFAULT NULL,
  finishedAt DATETIME DEFAULT NULL,
  routePath VARCHAR(100) DEFAULT NULL,
  sourceEventId BIGINT UNSIGNED DEFAULT NULL,
  payloadHash CHAR(40) DEFAULT NULL,
  payloadJson LONGTEXT DEFAULT NULL,
  resultJson LONGTEXT DEFAULT NULL,
  lastErrorCode VARCHAR(80) DEFAULT NULL,
  lastErrorMessage VARCHAR(255) DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_intent_key (intentKey),
  KEY idx_order_intent_claim (status, availableAt, priority, id),
  KEY idx_order_intent_fifo (fifoKey, status, id),
  KEY idx_order_intent_owner (uid, strategyCategory, pid, status, createdAt),
  KEY idx_order_intent_payload_hash (payloadHash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
