[INPUT]
    Name tail
    Path /var/log/xignal/backend-jsonl.log
    Parser json
    Tag xignal.backend
    Refresh_Interval 5
    Read_From_Head true

[FILTER]
    Name modify
    Match xignal.backend
    Add service backend
    Add app xignal

[OUTPUT]
    Name loki
    Match xignal.backend
    Host loki
    Port 3100
    Labels job=xignal-backend,service=backend,app=xignal
    Line_Format json
